### PR TITLE
Create LICENSE.md

### PR DESCRIPTION
**Pull request by T1eerth**
Created License

### CODE REVIEW

**Comment by avincodes** [comment]
Duplicate, unrequested PR. Will be considered spam

**Comment by T1eerth** [comment]
> Duplicate, unrequested PR. Will be considered spam

I just tried to help if you think its a spam , its all ok mate

**Comment by avincodes** [comment]
You literally sent two PRs of the same file. that is spam!

**Comment by T1eerth** [comment]
> You literally sent two PRs of the same file. that is spam!

Bro like my hostel wifi is not that good I thought that the first pr did not get generated so i tried second time. Sorry i am also new to github , i was just trying to help mate!

**Comment by T1eerth** [comment]
I can still make a License if you want

**Comment by avincodes** [comment]
Oh I am sorry for blaming you without knowing the situation! Are you participating in Hacktoberfest?

**Comment by T1eerth** [comment]
> Oh I am sorry for blaming you without knowing the situation! Are you participating in Hacktoberfest? 

All fine mate, no man i am just exploring around and learning new things..

**Comment by avincodes** [comment]
I recommend that you check it out to contribute to open source! and win some cool swags!

**Pull request closed without merging**
