### PR TITLE
Call booking page created 

### PR DESCRIPTION
**Pull request by VANSHAJB10**
Page is created with html file named -- contact_index.html
and
LinkedIn to the home page by creating one more item in the <ul>

### CODE REVIEW

**Comment by avincodes** [comment]
Hey @VANSHAJB10 thanks for the PR. Does this work in your local environment? And if so, can you provide me with a screenshot of it? Thank you!

**Comment by VANSHAJB10** [comment]
> Hey @VANSHAJB10 thanks for the PR. Does this work in your local environment? And if so, can you provide me with a screenshot of it? Thank you!

Yes, I have tested it locally and it is working perfectly fine

**Comment by VANSHAJB10** [comment]
Screenshot (6902)

**Comment by avincodes** [comment]
Looks good, can you change the text below the book a call with avin section as well? Thank you!

**Comment by VANSHAJB10** [comment]
> Looks good, can you change the text below the book a call with Avin section as well? Thank you!

Can you tell me exactly what thing you want to put in this paragraph?
I intentionally kept it sample text, so that you can add whatever you feel is good to be mentioned here

**Comment by VANSHAJB10** [comment]
> > Looks good, can you change the text below the book a call with Avin section as well? Thank you!
> 
> Can you tell me exactly what thing you want to put in this paragraph? I intentionally kept it sample text, so that you can add whatever you feel is good to be mentioned here

@avincodes

**Comment by avincodes** [comment]
@VANSHAJB10 if you're participating in HF feel free to open another PR and ill be happy to merge that, since this was originally an HF issue too! :)  

PR Looks good to go apart from that!

**Comment by avincodes** [comment]
> > > Looks good, can you change the text below the book a call with Avin section as well? Thank you!
> > 
> > 
> > Can you tell me exactly what thing you want to put in this paragraph? I intentionally kept it sample text, so that you can add whatever you feel is good to be mentioned here
> 
> @avincodes

Maybe change it to, Once a time is confirmed and email will follow with video conferencing information!

**Comment by VANSHAJB10** [comment]
> @VANSHAJB10 if you're participating in HF feel free to open another PR and ill be happy to merge that, since this was originally an HF issue too! :)
> 
> PR Looks good to go apart from that!

Okay

**Pull request closed without merging**
