### PR TITLE
Fix deps

### PR DESCRIPTION
**Pull request by bhishekprajapati**
1. Enforced a specific node and npm version for the project. One of the project dependency name `fibers`  having issues with node version greater than v15.
2. Updated dependencies.
3. updated .gitignore to ignore tracking of node_modules folder.

### CODE REVIEW

**Comment by avincodes** [comment]
@bhishekprajapati changes LGTM! Are you able to remove the Visual Studio Developer tool requirement too? Any possibility of that?

**Comment by bhishekprajapati** [comment]
@avincodes Project does not depends on any specific set of tools! It can run from any IDE. The only things is node version has to be v15. That's all!

**Comment by avincodes** [comment]
Do you have a Discord account? Mind if I contact you there?

**Comment by bhishekprajapati** [comment]
> Do you have a Discord account? Mind if I contact you there?

Sure! Drop your discord username here

**Comment by avincodes** [comment]
> > Do you have a Discord account? Mind if I contact you there?
> 
> Sure! Drop your discord username here

@bhishekprajapati @avinhere

**Pull request merged**
