### PR TITLE
fix: preload title

### LINKED ISSUE #18: Fix Preloader Title
The task related to this issue is to 

- [ ] Fix the preloader bug where the word ```kydzs``` pops up as the page title during the preloader screen. Please replace this to ```avinhere``` (Same content as main page).

### PR DESCRIPTION
**Pull request by khalatevarun**
Fixes #18

### CODE REVIEW

**Comment by avincodes** [comment]
@khalatevarun can you please attach a screen recording of this...

**Comment by avincodes** [comment]
Any update @khalatevarun?

**Comment by khalatevarun** [comment]
Hey @avincodes will update you in a while

**Comment by avincodes** [comment]
Sure take your time @khalatevarun, was just checking if you are still working on it!

**Comment by avincodes** [comment]
Reminder, @khalatevarun .

**Comment by khalatevarun** [comment]
Hey @avincodes, due to change in config I am not able to run the project on my machine. Vue cli is not being installed correctly. Could you please check if the expected changes are reflected ?

**Comment by avincodes** [comment]
Oh yes sure!!

**Review by avincodes — APPROVED** [review]
Yep! They seem good to go!

**Comment by avincodes** [comment]
Great work @khalatevarun! Thank you for contributing!

**Pull request merged**
