### PR TITLE
added changes in readme file

### PR DESCRIPTION
**Pull request by DeepakRana07**
i have mention  desired changes  in your readme file i hope u like it  Plz accpet my PR for hacktoberfest2022!

### CODE REVIEW

**Review by avincodes — CHANGES_REQUESTED** [review]
This was not the intended fix for issue #13. The issue clearly asks for a new header to be designed and you have made a few text changes to the readme file. Do let me know if you would be able to make the intended changes or I will re-assign this.

**Comment by avincodes** [comment]
Any update @DeepakRana07

**Comment by avincodes** [comment]
Close due to inactivity.

**Comment by DeepakRana07** [comment]
Bro y have spam me ! i am totally  new to this opensource that why i just tried
your repo i really want your readme file to become more attractive but i know few only thats y this happen

I am really sorry

**Comment by avincodes** [comment]
Please dont do it again, I have removed the tag.

**Comment by DeepakRana07** [comment]
Thanku so much

**Pull request closed without merging**
