### PR TITLE
Pre Loader Screen

### PR DESCRIPTION
**Pull request by Suraj-Bhandarkar-S**
#2 Pre-loader Screen Added for the existing website
 
Loader

### CODE REVIEW

**Comment by avincodes** [comment]
Hey @Suraj-Bhandarkar-S is it possible to add something like a logo for this?

**Comment by Suraj-Bhandarkar-S** [comment]
Yes, If you can share me the Logo Image I can Try to add

**Comment by avincodes** [comment]
Sure @Suraj-Bhandarkar-S I will share with you, just give me some time! In the meantime I will keep this assigned to you!

**Comment by Suraj-Bhandarkar-S** [comment]
Cool :)

**Comment by Suraj-Bhandarkar-S** [comment]
@avincodes Any Updates?

**Comment by avincodes** [comment]
hey @Suraj-Bhandarkar-S I was not able to find a logo but feel free to use a wavy line progress bar with the color used on the site! Thank you!

**Comment by Suraj-Bhandarkar-S** [comment]
image
 
Added the new Wave form loader

**Comment by avincodes** [comment]
This is perfect!! Just what I had in mind! Thank you @Suraj-Bhandarkar-S!

**Pull request merged**
